# Permalinks
permalink: /:year-:month-:day/:title

# Setup
title: Yeolam Sung
baseurl: ''
url: 'https://blog.developersung.com'

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
rouge:
  theme: github

# About
author:
  name: bunny-goorm
  url: https://blog.developersung.com/
  email: developersung13
  github: bunny-goorm
  twitter: developersung

# Custom vars
version: 3.4.1
github:
  repo: https://github.com/bunny-goorm/developersung-blog.git

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
