# Permalinks
permalink: /:year-:month-:day/:title

# Setup
title: Yeolam Sung
baseurl: ""
url: "https://agetbase.com"

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
rouge:
  theme: github

# About
author:
  name: agetbase
  url: https://agetbase.com/
  email: agetbase
  github: agetbase
  twitter: agetbase

# Custom vars
version: 3.4.1
github:
  repo: https://github.com/agetbase/record.git

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
